layout_spectrum: 0.3653906
typography_spectrum: 0.2537056
color:
  saturation: 0.7410461
  lightness: 0.1490991
  brandStrength: 0.2231915
  rhythmicContrast: 0.2184763
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: Familyandfriends
